### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by alexliyang** [jylc/DFWAPCP#1]
不想用opengl和qt，就是简单shell下模拟一下的参考有吗？能有个完整的处理流程吗？

**Comment by jylc** [comment]
github上有其他人实现的python版本，我这个主要用的opencv，写的时候没规划好，代码比较乱

**Comment by alexliyang** [comment]
python 版本的没有看到code， 你有python的吗？

**Comment by jylc** [comment]
https://github.com/yzhq97/distortion-free-wide-angle.pytorch 这不是一搜就有么

**Comment by alexliyang** [comment]
这个没打开看，我以为是用深度学习训练模型的方案呢。
现在用你的代码来跑，就是那个计算能量最小化的地方通不过，getImageVerticesBySolving 函数运行到：
        CostFunction* face_energy = new AutoDiffCostFunction<FaceObjectTermEnergy, 2, 1, 1>(
            new FaceObjectTermEnergy(m_stereo_mesh[i].x, m_stereo_mesh[i].y, w, m, S));
        problem.AddResidualBlock(face_energy, nullptr, &vertices[i].first, &vertices[i].second);

直接报错了，不知道是环境的是还是怎么，之前没用过ceres，我再学习学习。
你之前跑通了？

**Comment by jylc** [comment]
两个我都跑通过了，不过时间有点久忘了怎么整了。可能是环境的原因吧，这个你要自己弄了。建议你还是用上面python版的，ceres在一般配置的电脑上跑起来是有点慢的。

**Comment by alexliyang** [comment]
配置ceres环境的问题，现在能跑通了，目前看到的问题是，多次迭代后，如果用mixedmesh边缘部分还是会有不合适的地方，特别是头部头发边缘会有凹凸感。

多谢多谢了。
